### PR TITLE
Adapt bonnie.toml for windows

### PR DESCRIPTION
**Pull request by Mazwak**
I could not test is, as I have an error on 'setup'

```
   Compiling web-sys v0.3.55
   Compiling wasm-bindgen-futures v0.4.28
   Compiling actix-web v4.0.0-beta.15
   Compiling perseus-cli v0.3.2 (S:\Simon\Rust\perseus\packages\perseus-cli)
error[E0107]: this trait takes 0 generic arguments but 1 generic argument was supplied
   --> C:\Users\Maz\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-4.0.0-beta.15\src\service.rs:288:6
    |
288 | impl Resource<Url> for ServiceRequest {
    |      ^^^^^^^^----- help: remove these generics
    |      |
    |      expected 0 generic arguments
    |
note: trait defined here, with 0 generic parameters
   --> C:\Users\Maz\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-router-0.5.0-rc.1\src\resource_path.rs:5:11
    |
5   | pub trait Resource {
    |           ^^^^^^^^

error[E0046]: not all trait items implemented, missing: `Path`
   --> C:\Users\Maz\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-4.0.0-beta.15\src\service.rs:288:1
    |
288 | impl Resource<Url> for ServiceRequest {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `Path` in implementation
    |
    = help: implement the missing item: `type Path = Type;`

Some errors have detailed explanations: E0046, E0107.
For more information about an error, try `rustc --explain E0046`.
error: could not compile `actix-web` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

### CODE REVIEW

**Comment by arctic-hen7** [comment]
Ah, that's the error I've been getting on CI. It seems that the new Actix Web beta is breaking something in the dependency tree. I'll fix this very soon, and then if you merge my changes into your branch it should hopefully work.

**Comment by arctic-hen7** [comment]
Okay, if you merge my changes in `main`, everything should hopefully work now!

**Comment by Mazwak** [comment]
Setup went fine after a small tweak.
Will test more tomorrow

**Comment by arctic-hen7** [comment]
Great, thanks! Let me know when you think this is ready to merge and I'll review it then.

**Comment by Mazwak** [comment]
## Untested

- ci-prep
- copy-subcrates (but is called by setup)
- publish
- release

## Tested

### build

LOTS of the same errors.

```
error[E0277]: the trait bound `SsrNode: sycamore::generic_node::Html` is not satisfied
   --> examples\basic\.perseus\builder\src/bin/export.rs:163:33
    |
163 |     let plugins = get_plugins::<SsrNode>();
    |                                 ^^^^^^^ the trait `sycamore::generic_node::Html` is not implemented for `SsrNode`
    |
note: required by a bound in `get_plugins`
   --> S:\Simon\Rust\perseus\examples\tiny\src\lib.rs:3:1
    |
3   | / define_app! {
4   | |     templates: [
5   | |         Template::<G>::new("index").template(|_| {
6   | |             view! {
...   |
15  | |     })
16  | | }
    | |_^ required by this bound in `get_plugins`
    = note: this error originates in the macro `$crate::define_plugins` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `SsrNode: sycamore::generic_node::Html` is not satisfied
   --> examples\basic\.perseus\builder\src/bin/export.rs:163:19
    |
163 |     let plugins = get_plugins::<SsrNode>();
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `sycamore::generic_node::Html` is not implemented for `SsrNode`
    |
note: required by a bound in `perseus::plugins::plugins_list::Plugins`
   --> S:\Simon\Rust\perseus\packages\perseus\src\plugins\plugins_list.rs:10:23
    |
10  | pub struct Plugins<G: Html> {
    |                       ^^^^ required by this bound in `perseus::plugins::plugins_list::Plugins`

error[E0599]: no method named `run` found for struct `perseus::plugins::functional::FunctionalPluginAction` in the current scope
   --> examples\basic\.perseus\builder\src/bin/export.rs:174:18
    |
174 |                 .run(err.to_string(), plugins.get_plugin_data());
    |                  ^^^ method not found in `perseus::plugins::functional::FunctionalPluginAction<std::string::String, ()>`
    |
   ::: S:\Simon\Rust\perseus\packages\perseus\src\plugins\action.rs:10:8
    |
10  |     fn run(&self, action_data: A, plugin_data: &HashMap<String, Box<dyn Any + Send>>) -> R2;
    |        --- the method is available for `perseus::plugins::functional::FunctionalPluginAction<std::string::String, ()>` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use perseus::plugins::action::PluginAction;
    |

error[E0599]: the method `get_plugin_data` exists for struct `perseus::plugins::plugins_list::Plugins<SsrNode>`, but its trait bounds were not satisfied
   --> examples\basic\.perseus\builder\src/bin/export.rs:174:47
    |
174 |                 .run(err.to_string(), plugins.get_plugin_data());
    |                                               ^^^^^^^^^^^^^^^ method cannot be called on `perseus::plugins::plugins_list::Plugins<SsrNode>` due to unsatisfied trait bounds
    |
   ::: C:\Users\Maz\.cargo\registry\src\github.com-1ecc6299db9ec823\sycamore-0.7.1\src\generic_node\ssr_node.rs:47:1
```

### check

OK

### check-branch

OK (it says "unimplemented)

### dev

#### example

OK. I’m not sure you really want to call it through "bonnie dev example basic serve". "serve" is implicit to me.

#### export-serve

NOK. Build ok, but I’m missing "serve" binary.

#### export-serve-deploy-relative

NOK. like export-serve. Moreover, I don’t understand what it is usefull for.

### replace-versions

OK (it says "unimplemented)

### setup

OK

### site (all subs)

NOK. I don’t have "concurrently"

### test

Build fails, see "build".

I didn’t look at test.sh, so it just says "not implemented"

## Suggestions

There should be a command or help to list dependencies (serve, concurrently, geckodriver, tailwindcss, ?).
And maybe a command to install them, if just an npm install.

test.ps1 might be written. Not sure you need perseus to be testable under windows though.

"dev example" should be serve by default, or at all.

**Comment by arctic-hen7** [comment]
Thanks for all your work! The reason `dev example` doesn't serve is to provide flexibility. What it's actually doing is running the local, bleeding edge version of the CLI (not the one on crates.io) so that I can test each command. For example, sometimes I'll be working on functionality in the server, and I'll need `serve`, but other times I'll want to `export`. That command basically just proxies the local version of the CLI.

`export-serve` is deprecated now, and I'll remove it soon, so don't worry about that.

`export-serve-deploy-relative` deploys the given example to static files and then hosts them at a relative path `/relative` rather than at the root, allowing testing of that functionality, which can be easily broken. Admittedly, that could be much better explained!

`setup` is supposed to list all the dependencies, but I think it's gotten a bit out of date. `serve` and `concurrently` can both be installed from `npm`, as can `tailwindcss`. `geckodriver` needs to be installed through system tools. 

That testing script would be really useful to have working for Windows if possible, though I completely understand if you don't want to do that now.

The untested scripts should all be fine, they're for my usage only pretty much. As long as `copy-subcrates` works that should be good.

**Comment by arctic-hen7** [comment]
I'm not sure what's going on with your build there, that looks very strange. Have you tried `cargo clean` to try to reset things to a reasonable state?

(Also, as a side note, you've probably realized this by now but don't delete `examples/basic/.perseus/`, it's where the `.perseus/` folder is actually developed.)

**Comment by Mazwak** [comment]
cargo clean got rid of compilation errors

**Comment by arctic-hen7** [comment]
Fantastic! Is this ready for review then?

**Comment by Mazwak** [comment]
Depends.

Do you want to release with or without dependency check ?

There’s no dependency check for 'generic' either.

**Comment by Mazwak** [comment]
I’m also wondering. Since you will need some dev dependency, couldn’t it also ask for (git bash/msys2) to use bonnie on windows ?

It already needs rust + rust-wasm and npm.

**Comment by arctic-hen7** [comment]
I reckon putting those dependencies in the contributing documentation is fine, and we can list then at the end of `setup` again. It doesn't have to be too fancy.

**Comment by arctic-hen7** [comment]
@Mazwak I've made some changes to the `copy-subcrates` script needed for #59, would you mind updating this to work with that? After that, if you're ready, I can review this and we can merge it.

**Comment by Mazwak** [comment]
I see you added a lot of sed.

find and sed do not exist on windows, by default.

So, to use the bonnie commands, there are various solutions :

- Tell people to install fd-find and sd rust binaries and adapt bonnie.toml (my pref)
- Tell people to install gnu win32 find and sed
- Use Git Bash instead of powershell
- Do not bother with windows, just says "not implement for windows" for everything

What do you think ?

**Comment by arctic-hen7** [comment]
Yeah, unfortunately that's required to support engines. 

The other possibility is to migrate as much of that as possible to Rust scripts that can run cross platform, what do you think of that?

**Comment by Mazwak** [comment]
It is becoming too involved just to test the docs on windows.
My main objective is to translate the docs. I can setup a linux box to test how it renders.

Making rust scripts is still a good idea, but I would prefer to focus on the docs first.
Reject this PR, and make a TODO somewhere, maybe an enhancement bug.

**Comment by arctic-hen7** [comment]
Yeah understandable. Well thank you very much for all your efforts!

With regards to translating the docs, would you mind holding off on the `next` folder until the end of the week? I'm refactoring several things for the next release, which adds a significant number of new features, and I just need to alter a few things so that everything's coherent. It shouldn't take long at all.

**Pull request closed without merging**
