### PR TITLE
Fix hydration by not inserting hydration keys in `<head>`

### PR DESCRIPTION
**Pull request by lukechu10**
TODO: this currently uses a hack that I'm not so proud of. I'll probably need to release a new version of sycamore to do this properly but at least the problem is fixed.

The problem with hydration was that hydration keys were rendered in the head strings. This would cause a conflict when hydrating because there would be multiple nodes with the same hydration keys. That, in turn, is because there are multiple calls to `render_to_string`, each which creates a new "hydration context".

Note that this is a PR against the `feat-sycamore-0.4.0` branch instead of the `main` branch.

### CODE REVIEW

**Comment by arctic-hen7** [comment]
Neat, thanks! If you don't mind, I'd like to roll back all the insane `Signal` stuff I've done before merging this.

**Comment by lukechu10** [comment]
Yeah no problem. Also there probably should be a function directly in sycamore to render to a string without hydration keys and hydration markers.

**Comment by lukechu10** [comment]
I released sycamore `v0.8.0-beta.5` which allowed me to remove the workaround. This should be ready now.

**Review by arctic-hen7 — APPROVED** [review]
Looks great, thanks so much!

One note: it might be good to alter the docs on `use_context_or_else` in Sycamore, I had no idea it actually added the result of the closure to the context.

**Comment by lukechu10** [comment]
> One note: it might be good to alter the docs on `use_context_or_else` in Sycamore, I had no idea it actually added the result of the closure to the context.

Yeah, I should probably make that clearer in the docs. Didn't realize it might have meant something else.

**Pull request merged**
