### PR TITLE
docs(0.3.4): readability improvements

### PR DESCRIPTION
**Pull request by ryanrussell**
Signed-off-by: Ryan Russell <git@ryanrussell.org>

### CODE REVIEW

**Review by arctic-hen7 — APPROVED** [review]
Great work, thank you very much!

**Comment by ryanrussell** [comment]
I see a few other little things in other docs versions... Couple questions

1. Should changes be made in `docs/0.4.0` or `docs/next` or both? Is `next` just a symlink?

2. Do you want me to do the same for the older doc versions or just let them rip? Two minutes to fix, but doubt many people are going back in time :)

-r

**Comment by arctic-hen7** [comment]
The `next` and `0.4.0` docs are distinct (though they're unified before a release), so changes would need to be made to both. Right now, I think it should be fine to make them to `next` and then just copy that all to `0.4.0`.

As for the older docs, that's up to you! I don't really mind either way.

**Comment by arctic-hen7** [comment]
@ryanrussell do you want to make those changes in this PR, or shall I merge this and you can make them in another PR?

**Comment by ryanrussell** [comment]
Just merge this one. I'm abroad with limited connectivity... Will send the rest when I can.

**Pull request merged**
