### PR TITLE
Update Sycamore to v0.6.0

### PR DESCRIPTION
**Pull request by lukechu10**
Updates sycamore to 0.6.0, removes patch dependencies

### CODE REVIEW

**Comment by lukechu10** [comment]
For some reason, clicking on links causes a context error.

**Comment by lukechu10** [comment]
Found it. This line here is not being called inside a reactive scope so it can't access the context:
https://github.com/arctic-hen7/perseus/blob/main/packages/perseus/src/router.rs#L145

That's because it's called when the anchor is clicked which happens during the global scope.

**Review by arctic-hen7 — APPROVED** [review]
This looks really great, thanks so much!

**Comment by arctic-hen7** [comment]
Okay that makes a lot of sense for the context error. Given though that `match_route` can't take any arguments, how would that be fixed? I'm only providing the routes in context because of the restrictions of the `Route` trait...

**Comment by arctic-hen7** [comment]
Would you mind quickly running `cargo fmt` so tests pass?

**Comment by lukechu10** [comment]
> Would you mind quickly running `cargo fmt` so tests pass?

Done

**Comment by lukechu10** [comment]
> I'm only providing the routes in context because of the restrictions of the `Route` trait

What kind of restrictions are you thinking about? Object-safety? The way I would do it would be to use a global variable since there is only 1 router per app (albeit not being very idiomatic in Rust).

Alternatively, I could change something in Sycamore itself to prevent the router from handling click events. This way, we could attach our own click handler and manually call `navigate`. This is probably cleaner and we'll probably a config like this in Sycamore anyways.

**Review by arctic-hen7 — APPROVED** [review]
All looks good!

**Comment by arctic-hen7** [comment]
I'll fix the broken links issue after this is merged as part of the fixes to #8, so this should be good to merge if you're done with it.

**Comment by lukechu10** [comment]
Alright. I'm done then.

**Comment by arctic-hen7** [comment]
Thanks so much, this is really helpful!

**Pull request merged**
