### PR TITLE
Minor code improvements

### PR DESCRIPTION
**Pull request by Asha20**

### CODE REVIEW

**Review by arctic-hen7 — APPROVED** [review]
This is really great, thank you very much!

I'll say that the changes to `ErrorPages` don't constitute a breaking change because from looking at them I don't think they should break any user-facing code (and custom engines aren't supported yet), is that correct?

**Comment by arctic-hen7** [comment]
This seems to have some conflicts, are you able to resolve those?

**Comment by Asha20** [comment]
Alright, merge conflicts resolved.

Actually, I think this might be a breaking change because of the parameter type change from `status: &u16` to `status: u16`; see [this commit](https://github.com/arctic-hen7/perseus/pull/110/commits/c9c7a0b1482fedc368bac9157a472c7956cbb3f5). Looking through the commit diff I see that I also had to update the parameters of files inside `examples`.

**Comment by arctic-hen7** [comment]
I genuinely have no clue why that comment was in italics, sometimes the GitHub mobile app is magical.

I don't see any changes to the parameters that examples take, I think they've always taken owned values haven't they?

**Review by arctic-hen7 — APPROVED** [review]
If this isn't a breaking change, it's good to merge.

**Comment by arctic-hen7** [comment]
Yeah @Asha20 I'm pretty sure you've just needed to change some things in `.perseus/` (which we work on inside `examples/basic/`, I know...), which doesn't constitute a breaking change.

**Pull request merged**
